
services:
  react_app: 
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: react_api_list_container
    ports:
      - "80:80"
      - "443:443"

volumes:
  react_project:

  
